
const translations = {
    en: {
        'About Easetech': 'About Easetech',
        'Mission': 'Mission',
        "Partner and Customer": 'Partner and Customer',
        "Founded in 2021, Ease Tech proudly serves as a reliable companion for small and medium-sized enterprises on their journey to conquer the market. With the mission of creating an intelligent and efficient business environment, we continuously research and develop advanced technological solutions to help businesses optimize processes, save costs, and enhance productivity.": "Founded in 2021, Ease Tech proudly serves as a reliable companion for small and medium-sized enterprises on their journey to conquer the market. With the mission of creating an intelligent and efficient business environment, we continuously research and develop advanced technological solutions to help businesses optimize processes, save costs, and enhance productivity.",
        "By combining the in-depth experience of our expert team with modern technology, Ease Tech is committed to providing comprehensive solutions that meet the diverse needs of businesses. We understand that technology is not just a tool, but also a bridge that helps businesses succeed. Therefore, Ease Tech always places customers at the center, ready to listen and understand in order to offer the most suitable solutions.": "By combining the in-depth experience of our expert team with modern technology, Ease Tech is committed to providing comprehensive solutions that meet the diverse needs of businesses. We understand that technology is not just a tool, but also a bridge that helps businesses succeed. Therefore, Ease Tech always places customers at the center, ready to listen and understand in order to offer the most suitable solutions.",
        "For customers": "For customers",
        "Putting customers at the center:": "Putting customers at the center:",
        "Always listen to and understand the needs of customers in order to provide the most suitable and effective solutions.": "Always listen to and understand the needs of customers in order to provide the most suitable and effective solutions.",
        "Provide comprehensive solutions:": "Provide comprehensive solutions:",
        "Not only providing products but also offering professional consulting services, technical support, and maintenance warranty.": "Not only providing products but also offering professional consulting services, technical support, and maintenance warranty.",
        "Commitment to quality and effectiveness:": "Commitment to quality and effectiveness:",
        "Ensure that products and services meet high quality standards, helping customers optimize processes, save costs, and enhance productivity.": "Ensure that products and services meet high quality standards, helping customers optimize processes, save costs, and enhance productivity.",
        "For partners": "For partners",
        "Build long-term collaborative relationships:": "Build long-term collaborative relationships:",
        "Create a win-win collaborative environment, developing together and sharing the results. Unity and commitment to common goals have helped us achieve significant success over the years.": "Create a win-win collaborative environment, developing together and sharing the results. Unity and commitment to common goals have helped us achieve significant success over the years.",
        "Customer": "Customer",
        "Partner": "Partner",
        "Headquarters:": "Headquarters:",
        "Contact Easetech": "Contact Easetech",
        "Contact us now for quick support.": "Contact us now for quick support.",
        "Contact now": "Contact now",
        "Easetech provides comprehensive digital transformation solutions for businesses": "Easetech provides comprehensive digital transformation solutions for businesses",
        "Set a new standard starting today!": "Set a new standard starting today!",
        "Easetech - The Golden Partner": "Easetech - The Golden Partner",
        "for Businesses": "for Businesses",
        "Helping businesses successfully implement CRM solutions!": "Helping businesses successfully implement CRM solutions!",
        "Implementing & Building Systems": "Implementing & Building Systems",
        "Easetech is a leading provider in building and implementing ERP and CRM systems for small and medium-sized enterprises. With years of experience in the field, we deliver comprehensive solutions to help businesses optimize management processes, increase productivity, and enhance business efficiency.": "Easetech is a leading provider in building and implementing ERP and CRM systems for small and medium-sized enterprises. With years of experience in the field, we deliver comprehensive solutions to help businesses optimize management processes, increase productivity, and enhance business efficiency.",
        "Our team of experts will consult and design systems tailored to the specific characteristics and scale of each business, ensuring all customer requirements are met.": "Our team of experts will consult and design systems tailored to the specific characteristics and scale of each business, ensuring all customer requirements are met.",
        "Data Collection & Transformation": "Data Collection & Transformation",
        "Easetech will help you transform raw data into valuable insights. We provide professional data collection, cleansing, and transformation services, enabling you to create detailed analytical reports, develop new products, optimize marketing campaigns, and enhance customer experiences.": "Easetech will help you transform raw data into valuable insights. We provide professional data collection, cleansing, and transformation services, enabling you to create detailed analytical reports, develop new products, optimize marketing campaigns, and enhance customer experiences.",
        "With high-quality data, you can make informed business decisions and achieve exceptional success.": "With high-quality data, you can make informed business decisions and achieve exceptional success.",
        "User Training": "User Training",
        "Easetech offers customized user training programs tailored to each client. With a flexible training approach that combines theory and practice, we are committed to helping your employees quickly master the knowledge and skills needed to use the software, thereby improving work efficiency.": "Easetech offers customized user training programs tailored to each client. With a flexible training approach that combines theory and practice, we are committed to helping your employees quickly master the knowledge and skills needed to use the software, thereby improving work efficiency.",
        "Post-Implementation Support": "Post-Implementation Support",
        "Ease Tech is committed to partnering with clients throughout the entire process of using the system. With a team of highly experienced and skilled technicians, we provide professional post-implementation support services, ensuring that your system remains stable and efficient.": "Ease Tech is committed to partnering with clients throughout the entire process of using the system. With a team of highly experienced and skilled technicians, we provide professional post-implementation support services, ensuring that your system remains stable and efficient.",
        "We support customers through various channels such as phone, email, and remote assistance, ready to resolve any inquiries and issues in the shortest time possible.": "We support customers through various channels such as phone, email, and remote assistance, ready to resolve any inquiries and issues in the shortest time possible.",
        "Customer satisfaction is Ease Tech's top priority. We offer fast and efficient warranty services, ensuring customers can use our products with peace of mind. With flexible warranty options, customers can choose the most suitable form of warranty for their needs.":"Customer satisfaction is Ease Tech's top priority. We offer fast and efficient warranty services, ensuring customers can use our products with peace of mind. With flexible warranty options, customers can choose the most suitable form of warranty for their needs.",
        "Warranty": "Warranty",
        "Implementation & Services": "Implementation & Services",
        "Easetech - Partnering with Businesses": "Easetech - Partnering with Businesses",
        "Pentest and System Testing": "Pentest and System Testing",
        "Ease Tech's pentest and system testing services provide comprehensive solutions to protect your information systems from cyberattacks. With a team of experienced experts and advanced testing tools, we conduct thorough and in-depth assessments of your system, including internal networks, web applications, databases, and IoT devices.": "Ease Tech's pentest and system testing services provide comprehensive solutions to protect your information systems from cyberattacks. With a team of experienced experts and advanced testing tools, we conduct thorough and in-depth assessments of your system, including internal networks, web applications, databases, and IoT devices.",
        "Analysis of Assessment Reports": "Analysis of Assessment Reports",
        "Ease Tech's testing reports provide detailed information about identified vulnerabilities, their severity, root causes, and specific remediation recommendations. Our reports not only help you understand the current security posture of your system but also provide a clear roadmap for improving security levels.": "Ease Tech's testing reports provide detailed information about identified vulnerabilities, their severity, root causes, and specific remediation recommendations. Our reports not only help you understand the current security posture of your system but also provide a clear roadmap for improving security levels.",
        "Instead of waiting for attacks to happen, Ease Tech's Red Team service helps you proactively identify and fix security vulnerabilities. We act as sophisticated attackers to search for and exploit any security weaknesses in your system.": "Instead of waiting for attacks to happen, Ease Tech's Red Team service helps you proactively identify and fix security vulnerabilities. We act as sophisticated attackers to search for and exploit any security weaknesses in your system.",
        "Incident Response – Information Security": "Incident Response – Information Security",
        "When a cybersecurity incident occurs, Ease Tech will be your trusted partner. We provide professional incident response services, helping you quickly detect and address information security issues.": "When a cybersecurity incident occurs, Ease Tech will be your trusted partner. We provide professional incident response services, helping you quickly detect and address information security issues.",
        "Operational Support": "Operational Support",
        "Providing modern technological solutions for businesses": "Providing modern technological solutions for businesses",
        "Centralized Remote Support":"Centralized Remote Support",
        "Remote support services help you resolve all technical issues quickly, efficiently, and securely.": "Remote support services help you resolve all technical issues quickly, efficiently, and securely.",
        "Modern technology and an experienced team are always ready to serve you.": "Modern technology and an experienced team are always ready to serve you.",
        "System Operations Support": "System Operations Support",
        "Help your business operate systems stably and efficiently with advanced technology.": "Help your business operate systems stably and efficiently with advanced technology.",
        "Ensure absolute security for your data.": "Ensure absolute security for your data.",
        "Updates & Bug Fixes": "Updates & Bug Fixes",
        "Protect your system with regular patch updates and bug fixing services.": "Protect your system with regular patch updates and bug fixing services.",
        "Safety and ensuring optimal system performance.": "Safety and ensuring optimal system performance.",
        "Data Backup & Recovery": "Data Backup & Recovery",
        "Automated backup and quick recovery services help protect your business data securely.": "Automated backup and quick recovery services help protect your business data securely.",
        "Your data is always under control.": "Your data is always under control.",
        "Cloud Computing": "Cloud Computing",
        "The optimal solution for IT infrastructure": "The optimal solution for IT infrastructure",
        "IT Infrastructure Design": "IT Infrastructure Design",
        "Easetech understands that each business has unique requirements. Therefore, we offer customized cloud infrastructure design services to help businesses build a system tailored to their scale and specific needs.": "Easetech understands that each business has unique requirements. Therefore, we offer customized cloud infrastructure design services to help businesses build a system tailored to their scale and specific needs.",
        "From selecting a cloud service provider to designing system architecture, we cater to all customer requirements.": "From selecting a cloud service provider to designing system architecture, we cater to all customer requirements.",
        "Deploying Software Solutions on the Cloud": "Deploying Software Solutions on the Cloud",
        "Easetech offers simple and user-friendly solutions for deploying software applications on the Cloud. We help your business quickly get applications up and running without requiring significant investment in hardware and software infrastructure.": "Easetech offers simple and user-friendly solutions for deploying software applications on the Cloud. We help your business quickly get applications up and running without requiring significant investment in hardware and software infrastructure.",
        "With an intuitive interface and a clear deployment process, you can easily manage and adjust the system yourself.": "With an intuitive interface and a clear deployment process, you can easily manage and adjust the system yourself.",
        "Digital Transformation": "Digital Transformation",
        "Technology Consulting": "Technology Consulting",
        "Easetech provides comprehensive digital transformation consulting services, helping businesses seize opportunities in the digital era. With a team of experienced experts, we partner with businesses to develop effective digital transformation strategies, optimize workflows, enhance productivity, and minimize costs.": "Easetech provides comprehensive digital transformation consulting services, helping businesses seize opportunities in the digital era. With a team of experienced experts, we partner with businesses to develop effective digital transformation strategies, optimize workflows, enhance productivity, and minimize costs.",
        "Process Optimization": "Process Optimization",
        "EaseTech's process optimization consulting includes the following steps: current state analysis, new process design, implementation, and training. We work with businesses to comprehensively evaluate existing processes, identify bottlenecks, and propose optimal solutions.": "EaseTech's process optimization consulting includes the following steps: current state analysis, new process design, implementation, and training. We work with businesses to comprehensively evaluate existing processes, identify bottlenecks, and propose optimal solutions.",
        "Easetech is committed to accompanying businesses throughout the implementation process, ensuring the new processes operate efficiently.": "Easetech is committed to accompanying businesses throughout the implementation process, ensuring the new processes operate efficiently.",
        "Process Design and Modeling": "Process Design and Modeling",
        "Easetech utilizes modern tools and methods, such as BPMN and UML, to design and model processes. We offer flexible modeling solutions tailored to the specific characteristics and scale of each business.": "Easetech utilizes modern tools and methods, such as BPMN and UML, to design and model processes. We offer flexible modeling solutions tailored to the specific characteristics and scale of each business.",
        "Predictive Analytics": "Predictive Analytics",
        "Easetech provides professional predictive analytics services, enabling businesses to make more accurate decisions. By analyzing historical and current data, we develop precise forecasting models that help businesses predict market trends, customer demands, and factors influencing their operations.": "Easetech provides professional predictive analytics services, enabling businesses to make more accurate decisions. By analyzing historical and current data, we develop precise forecasting models that help businesses predict market trends, customer demands, and factors influencing their operations.",
        "Solutions - Services": "Solutions - Services",
        "Solutions": "Solutions",
        "Recruitment": "Recruitment",
        "Introduction": "Introduction",
        "Core Values - Vision": "Core Values - Vision",
        "Human Resources Team": "Human Resources Team",
        "For Employees": "For Employees",
        "Create a Professional Working Environment:": "Create a Professional Working Environment:",
        "Invest in facilities, technology, and training to create a modern and dynamic working environment.": "Invest in facilities, technology, and training to create a modern and dynamic working environment.",
        "Encourage Creativity and Innovation:": "Encourage Creativity and Innovation:",
        "Create conditions for employees to freely innovate, propose new ideas, and contribute to the company's development.": "Create conditions for employees to freely innovate, propose new ideas, and contribute to the company's development.",
        "Ensure good benefits:": "Ensure good benefits:",
        "Provide attractive compensation packages, opportunities for advancement, and career development to attract and retain talent.": "Provide attractive compensation packages, opportunities for advancement, and career development to attract and retain talent.",
        "Core values": "Core values",
        "of Easetech are built on the foundation of": "of Easetech are built on the foundation of",
        "innovation, reliability, and collaboration": "innovation, reliability, and collaboration",
        "We are constantly seeking new technologies and innovative solutions to provide our customers with the best experiences. Reliability is the foundation of all relationships; we are committed to accompanying our customers and partners on every journey. Finally, the spirit of collaboration is the key factor that enables us to create outstanding values together.": "We are constantly seeking new technologies and innovative solutions to provide our customers with the best experiences. Reliability is the foundation of all relationships; we are committed to accompanying our customers and partners on every journey. Finally, the spirit of collaboration is the key factor that enables us to create outstanding values together.",
        "Vision": "Vision",
        "of EaseTech is to become": "of EaseTech is to become",
        "the leading trusted technology partner": "the leading trusted technology partner",
        "for small and medium-sized enterprises in Vietnam. We aspire to create a world where technology is accessible and beneficial for everyone. EaseTech will continuously strive to simplify technology, helping businesses save time and costs while focusing on core activities. At the same time, we are committed to contributing to": "for small and medium-sized enterprises in Vietnam. We aspire to create a world where technology is accessible and beneficial for everyone. EaseTech will continuously strive to simplify technology, helping businesses save time and costs while focusing on core activities. At the same time, we are committed to contributing to",
        "the sustainable development of the community and society.": "the sustainable development of the community and society.",
        "Core Values – Vision": "Core Values – Vision",
        "With over 100 enthusiastic and creative employees, EaseTech proudly boasts a team of top experts in the field of information technology. The diversity of expertise and experience has created a dynamic and effective working environment, where everyone collaborates to solve complex problems and create valuable products and services. The spirit of unity and commitment to common goals has helped us achieve significant success over the years.": "With over 100 enthusiastic and creative employees, EaseTech proudly boasts a team of top experts in the field of information technology. The diversity of expertise and experience has created a dynamic and effective working environment, where everyone collaborates to solve complex problems and create valuable products and services. The spirit of unity and commitment to common goals has helped us achieve significant success over the years.",
        "Security Services - Information Safety": "Security Services - Information Safety",
        "Implementation": "Implementation",
        "Contact": "Contact",
        "Register for Consultation": "Register for Consultation",
        "Full Name": "Full Name",
        "Cellphone": "Cellphone",
        "Content": "Content",
        "Register Now": "Register Now",
        "Home Page": "Home Page",
        "Key clients of easetech": "Key clients of Easetech",
        "With many years of experience, EASETECH has become a trusted and reputable partner for numerous information technology projects, providing digital transformation solutions for businesses. With an unwavering desire and passion for continuous innovation, Gimasys always strives to fulfill its commitments to customers and partners to the best of its ability.": "With many years of experience, EASETECH has become a trusted and reputable partner for numerous information technology projects, providing digital transformation solutions for businesses. With an unwavering desire and passion for continuous innovation, Gimasys always strives to fulfill its commitments to customers and partners to the best of its ability.",
        "Want to make customers more satisfied and loyal? EaseTech's Contact Center solution will help you do that. With a multi-channel Contact Center system, we enable businesses to interact with customers seamlessly and effectively through phone, email, chat, and social media channels. As a result, businesses": "Want to make customers more satisfied and loyal? EaseTech's Contact Center solution will help you do that. With a multi-channel Contact Center system, we enable businesses to interact with customers seamlessly and effectively through phone, email, chat, and social media channels. As a result, businesses",
        "Easetech is committed to accompanying businesses throughout the implementation and operation of the system, ensuring that all activities run smoothly and efficiently.": "Easetech is committed to accompanying businesses throughout the implementation and operation of the system, ensuring that all activities run smoothly and efficiently.",
        "Want to make customers more satisfied and loyal? EaseTech's Contact Center solution will help you do that. With a multi-channel Contact Center system, we enable businesses to interact with customers seamlessly and effectively through phone, email, chat, and social media channels. As a result, businesses can": "Want to make customers more satisfied and loyal? EaseTech's Contact Center solution will help you do that. With a multi-channel Contact Center system, we enable businesses to interact with customers seamlessly and effectively through phone, email, chat, and social media channels. As a result, businesses can",
        "quickly capture customer needs, provide professional customer service 24/7, and enhance customer satisfaction": "quickly capture customer needs, provide professional customer service 24/7, and enhance customer satisfaction",
    },
    vi: {
        'About Easetech': 'Về Easetech',
        'Mission': "Sứ mệnh",
        "Partner and Customer": 'Đối tác và khách hàng',
        "Founded in 2021, Ease Tech proudly serves as a reliable companion for small and medium-sized enterprises on their journey to conquer the market. With the mission of creating an intelligent and efficient business environment, we continuously research and develop advanced technological solutions to help businesses optimize processes, save costs, and enhance productivity.": "Ra đời từ năm 2021, Ease Tech tự hào là người bạn đồng hành tin cậy của doanh nghiệp vừa và nhỏ trên hành trình chinh phục thị trường. Với sứ mệnh kiến tạo một môi trường kinh doanh thông minh và hiệu quả, chúng tôi không ngừng nghiên cứu và phát triển các giải pháp công nghệ tiên tiến, giúp doanh nghiệp tối ưu hóa quy trình, tiết kiệm chi phí và nâng cao năng suất.",
        "By combining the in-depth experience of our expert team with modern technology, Ease Tech is committed to providing comprehensive solutions that meet the diverse needs of businesses. We understand that technology is not just a tool, but also a bridge that helps businesses succeed. Therefore, Ease Tech always places customers at the center, ready to listen and understand in order to offer the most suitable solutions.": "Bằng việc kết hợp kinh nghiệm chuyên sâu của đội ngũ chuyên gia và công nghệ hiện đại, Ease Tech cam kết cung cấp các giải pháp toàn diện, đáp ứng đa dạng nhu cầu của doanh nghiệp. Chúng tôi hiểu rằng, công nghệ không chỉ là công cụ, mà còn là cầu nối giúp doanh nghiệp thành công. Chính vì vậy, Ease Tech luôn đặt khách hàng làm trung tâm, sẵn sàng lắng nghe và thấu hiểu để đưa ra những giải pháp phù hợp nhất.",
        "For customers": "Đối tác và khách hàng",
        "Putting customers at the center:": "Đặt khách hàng là trung tâm:",
        "Always listen to and understand the needs of customers in order to provide the most suitable and effective solutions.": "Luôn lắng nghe và thấu hiểu nhu cầu của khách hàng để đưa ra những giải pháp phù hợp và hiệu quả nhất.",
        "Provide comprehensive solutions:": "Các cung cấp giải phải toàn diện:",
        "Not only providing products but also offering professional consulting services, technical support, and maintenance warranty.": "Không chỉ cung cấp sản phẩm mà còn cung cấp dịch vụ tư vấn, hỗ trợ kỹ thuật và bảo trì bảo hành chuyên nghiệp.",
        "Commitment to quality and effectiveness:":"Cam kết chất lượng và hiệu quả:",
        "Ensure that products and services meet high quality standards, helping customers optimize processes, save costs, and enhance productivity.": "Đảm bảo các sản phẩm và dịch vụ đạt chất lượng cao, giúp khách hàng tối ưu hóa quy trình, tiết kiệm chi phí và nâng cao năng suất.",
        "For partners": "Đối với đối tác",
        "Build long-term collaborative relationships:": "Xây dựng mối quan hệ hợp tác lâu dài:",
        "Create a win-win collaborative environment, developing together and sharing the results. Unity and commitment to common goals have helped us achieve significant success over the years.": "Tạo dựng một môi trường hợp tác win-win, cùng nhau phát triển và chia sẻ thành quả. Đoàn kết và sự cam kết với mục tiêu chung đã giúp chúng tôi đạt được nhiều thành công trong những năm qua.",
        "Customer": "Khách hàng",
        "Partner": "Đối tác",
        "Headquarters:": "Trụ sở chính:",
        "Contact Easetech": "Liên hệ với Easetech",
        "Contact": "Liên hệ",
        "Contact us now for quick support.": "Liên hệ ngay để được hỗ trợ nhanh chóng.",
        "Contact now": "Liên hệ ngay",
        "Easetech provides comprehensive digital transformation solutions for businesses": "Easetech cung cấp giải pháp toàn diện về Chuyển đổi số cho doanh nghiệp",
        "Set a new standard starting today!": "Thiết lập tiêu chuẩn mới ngay ngày hôm nay!",
        "Easetech - The Golden Partner": "Easetech - Đối tác Vàng",
        "for Businesses": "của các doanh nghiệp",
        "Helping businesses successfully implement CRM solutions!": "Giúp doanh nghiệp triển khai Giải pháp CRM thành công!",
        "Implementing & Building Systems": "Triển khai & Xây dựng hệ thống",
        "Ease Tech is a leading provider in building and implementing ERP and CRM systems for small and medium-sized enterprises. With years of experience in the field, we deliver comprehensive solutions to help businesses optimize management processes, increase productivity, and enhance business efficiency.": "Easetech là đơn vị hàng đầu trong việc xây dựng và triển khai các hệ thống ERP và CRM cho doanh nghiệp vừa và nhỏ. Với kinh nghiệm nhiều năm trong lĩnh vực, chúng tôi cung cấp các giải pháp toàn diện, giúp doanh nghiệp tối ưu hóa quy trình quản lý, tăng năng suất lao động và nâng cao hiệu quả kinh doanh.",
        "Our team of experts will consult and design systems tailored to the specific characteristics and scale of each business, ensuring all customer requirements are met.": "Đội ngũ chuyên gia của chúng tôi sẽ tư vấn và thiết kế hệ thống phù hợp với từng đặc thù ngành nghề và quy mô của doanh nghiệp, đảm bảo đáp ứng mọi yêu cầu của khách hàng.",
        "Data Collection & Transformation": "Thu thập & Chuyển đổi dữ liệu",
        "Easetech will help you transform raw data into valuable insights. We provide professional data collection, cleansing, and transformation services, enabling you to create detailed analytical reports, develop new products, optimize marketing campaigns, and enhance customer experiences.": "Easetech sẽ giúp bạn biến dữ liệu thô thành những thông tin giá trị. Chúng tôi cung cấp dịch vụ thu thập, làm sạch và chuyển đổi dữ liệu chuyên nghiệp, giúp bạn xây dựng các báo cáo phân tích chi tiết, phát triển sản phẩm mới, tối ưu hóa chiến dịch marketing và nâng cao trải nghiệm khách hàng.",
        "With high-quality data, you can make informed business decisions and achieve exceptional success.":  "Với dữ liệu chất lượng cao, bạn sẽ có thể đưa ra những quyết định kinh doanh đúng đắn và đạt được thành công vượt trội.",
        "User Training": "Đào tạo người dùng",
        "Easetech offers customized user training programs tailored to each client. With a flexible training approach that combines theory and practice, we are committed to helping your employees quickly master the knowledge and skills needed to use the software, thereby improving work efficiency.":"Easetech cung cấp các chương trình đào tạo người dùng được thiết kế riêng cho từng khách hàng. Với phương pháp đào tạo linh hoạt, kết hợp lý thuyết và thực hành, chúng tôi cam kết giúp nhân viên của bạn nhanh chóng nắm vững kiến thức và kỹ năng sử dụng phần mềm, nâng cao hiệu suất làm việc.",
        "Post-Implementation Support": "Hỗ trợ sau triển khai",
        "Ease Tech is committed to partnering with clients throughout the entire process of using the system. With a team of highly experienced and skilled technicians, we provide professional post-implementation support services, ensuring that your system remains stable and efficient.": "Easetech cam kết đồng hành cùng khách hàng trong suốt quá trình sử dụng hệ thống. Với đội ngũ kỹ thuật viên giàu kinh nghiệm và chuyên môn cao, chúng tôi cung cấp dịch vụ hỗ trợ sau vận hành chuyên nghiệp, đảm bảo hệ thống của bạn luôn hoạt động ổn định và hiệu quả.",
        "We support customers through various channels such as phone, email, and remote assistance, ready to resolve any inquiries and issues in the shortest time possible.": "Chúng tôi hỗ trợ khách hàng qua nhiều kênh khác nhau như điện thoại, email và hỗ trợ từ xa, sẵn sàng giải quyết mọi thắc mắc và sự cố trong thời gian ngắn nhất.",
        "Customer satisfaction is Ease Tech's top priority. We offer fast and efficient warranty services, ensuring customers can use our products with peace of mind. With flexible warranty options, customers can choose the most suitable form of warranty for their needs.":"Sự hài lòng của khách hàng là ưu tiên hàng đầu của Ease Tech. Chúng tôi cung cấp dịch vụ bảo hành nhanh chóng, hiệu quả, giúp khách hàng yên tâm sử dụng sản phẩm. Với chế độ bảo hành linh hoạt, khách hàng có thể lựa chọn hình thức bảo hành phù hợp nhất với nhu cầu của mình.",
        "Warranty": "Bảo hành",
        "Implementation & Services": "Triển khai & Dịch vụ",
        "Easetech - Partnering with Businesses": "Easetech - Đồng hành cùng doanh nghiệp",
        "Pentest and System Testing": "Pentest và Kiểm thử hệ thống",
        "Ease Tech's pentest and system testing services provide comprehensive solutions to protect your information systems from cyberattacks. With a team of experienced experts and advanced testing tools, we conduct thorough and in-depth assessments of your system, including internal networks, web applications, databases, and IoT devices.": "Dịch vụ pentest và kiểm thử hệ thống của Ease Tech là giải pháp toàn diện giúp doanh nghiệp bảo vệ hệ thống thông tin trước các cuộc tấn công mạng. Với đội ngũ chuyên gia giàu kinh nghiệm và công cụ kiểm thử hiện đại, chúng tôi thực hiện đánh giá sâu sắc và toàn diện hệ thống của bạn, từ mạng nội bộ, ứng dụng web, cơ sở dữ liệu đến các thiết bị IoT.",
        "Analysis of Assessment Reports": "Phân tích báo cáo đánh giá",
        "Ease Tech's testing reports provide detailed information about identified vulnerabilities, their severity, root causes, and specific remediation recommendations. Our reports not only help you understand the current security posture of your system but also provide a clear roadmap for improving security levels.": "Báo cáo kiểm thử của Ease Tech cung cấp thông tin chi tiết về các lỗ hổng được phát hiện, mức độ nghiêm trọng, nguyên nhân gốc rễ và các khuyến nghị khắc phục cụ thể. Báo cáo của chúng tôi không chỉ giúp bạn hiểu rõ tình trạng bảo mật hiện tại của hệ thống mà còn cung cấp lộ trình rõ ràng để nâng cao mức độ bảo mật.",
        "Instead of waiting for attacks to happen, Ease Tech's Red Team service helps you proactively identify and fix security vulnerabilities. We act as sophisticated attackers to search for and exploit any security weaknesses in your system.": "Thay vì chờ đợi các cuộc tấn công xảy ra, dịch vụ Red Team của Ease Tech giúp bạn chủ động phát hiện và khắc phục các lỗ hổng bảo mật. Chúng tôi sẽ đóng vai trò là những kẻ tấn công tinh vi để tìm kiếm và khai thác mọi lỗ hổng bảo mật trong hệ thống của bạn.",
        "Incident Response – Information Security": "Ứng phó sự cố An ninh – An toàn thông tin",
        "When a cybersecurity incident occurs, Ease Tech will be your trusted partner. We provide professional incident response services, helping you quickly detect and address information security issues.": "Khi sự cố an ninh mạng xảy ra, Ease Tech sẽ là người bạn đồng hành đáng tin cậy của bạn. Chúng tôi cung cấp dịch vụ ứng phó sự cố chuyên nghiệp, giúp bạn nhanh chóng phát hiện và xử lý các sự cố an toàn thông tin.",
        "Operational Support": "Hỗ trợ vận hành",
        "Providing modern technological solutions for businesses": "Cung cấp các giải pháp công nghệ hiện đại cho doanh nghiệp",
        "Centralized Remote Support": "Hỗ trợ tập trung từ xa",
        "Remote support services help you resolve all technical issues quickly, efficiently, and securely.": "Dịch vụ hỗ trợ từ xa giúp bạn giải quyết mọi vấn đề kỹ thuật một cách nhanh chóng, hiệu quả và an toàn.",
        "Modern technology and an experienced team are always ready to serve you.": "Công nghệ hiện đại và đội ngũ giàu kinh nghiệm luôn sẵn sàng phục vụ bạn.",
        "System Operations Support": "Hỗ trợ vận hành hệ thống",
        "Help your business operate systems stably and efficiently with advanced technology.": "Giúp doanh nghiệp của bạn vận hành hệ thống một cách ổn định và hiệu quả bằng công nghệ tiên tiến.",
        "Ensure absolute security for your data.": "Đảm bảo bảo mật tuyệt đối cho dữ liệu của bạn.",
        "Updates & Bug Fixes": "Cập nhật & sửa lỗi",
        "Protect your system with regular patch updates and bug fixing services.": "Bảo vệ hệ thống của bạn với dịch vụ cập nhật bản vá và sửa lỗi thường xuyên.",
        "Safety and ensuring optimal system performance.": "An toàn và đảm bảo hiệu suất hệ thống tối ưu.",
        "Data Backup & Recovery": "Sao lưu & phục hồi dữ liệu",
        "Automated backup and quick recovery services help protect your business data securely.": "Dịch vụ sao lưu tự động và phục hồi nhanh chóng giúp bạn bảo vệ dữ liệu doanh nghiệp an toàn.",
        "Your data is always under control.": "Dữ liệu của bạn luôn trong tầm kiểm soát.",
        "Cloud Computing": "Điện toán đám mây",
        "The optimal solution for IT infrastructure": "Giải pháp tối ưu cho hạ tầng công nghệ thông tin",
        "IT Infrastructure Design": "Thiết kế hạ tầng Công nghệ thông tin",
        "Easetech understands that each business has unique requirements. Therefore, we offer customized cloud infrastructure design services to help businesses build a system tailored to their scale and specific needs.": "Easetech hiểu rằng mỗi doanh nghiệp có những yêu cầu khác nhau. Vì vậy, chúng tôi cung cấp dịch vụ thiết kế hạ tầng đám mây tùy biến, giúp doanh nghiệp xây dựng một hệ thống phù hợp với quy mô và đặc thù của mình.",
        "From selecting a cloud service provider to designing system architecture, we cater to all customer requirements.": "Từ việc lựa chọn nhà cung cấp dịch vụ đám mây đến việc thiết kế kiến trúc hệ thống, chúng tôi đều đáp ứng theo yêu cầu của khách hàng.",
        "Deploying Software Solutions on the Cloud": "Triển khai giải pháp phần mềm trên Cloud",
        "Easetech offers simple and user-friendly solutions for deploying software applications on the Cloud. We help your business quickly get applications up and running without requiring significant investment in hardware and software infrastructure.": "Easetech mang đến giải pháp triển khai phần mềm ứng dụng trên Cloud một cách đơn giản và dễ sử dụng. Chúng tôi giúp doanh nghiệp bạn nhanh chóng đưa các ứng dụng vào hoạt động mà không cần phải đầu tư quá nhiều vào hạ tầng phần cứng và phần mềm.",
        "With an intuitive interface and a clear deployment process, you can easily manage and adjust the system yourself.": "Với giao diện trực quan và quy trình triển khai rõ ràng, bạn có thể tự quản lý và điều chỉnh hệ thống một cách dễ dàng.",
        "Digital Transformation": "Chuyển đổi số",
        "Technology Consulting": "Tư vấn công nghệ",
        "Easetech provides comprehensive digital transformation consulting services, helping businesses seize opportunities in the digital era. With a team of experienced experts, we partner with businesses to develop effective digital transformation strategies, optimize workflows, enhance productivity, and minimize costs.": "Easetech cung cấp dịch vụ tư vấn chuyển đổi số toàn diện, giúp doanh nghiệp nắm bắt cơ hội trong kỷ nguyên số. Với đội ngũ chuyên gia giàu kinh nghiệm, chúng tôi đồng hành cùng doanh nghiệp xây dựng chiến lược chuyển đổi số hiệu quả, tối ưu hóa quy trình làm việc, nâng cao năng suất và giảm thiểu chi phí.",
        "Process Optimization": "Tối ưu quy trình",
        "EaseTech's process optimization consulting includes the following steps: current state analysis, new process design, implementation, and training. We work with businesses to comprehensively evaluate existing processes, identify bottlenecks, and propose optimal solutions.": "Quá trình tư vấn tối ưu quy trình của EaseTech bao gồm các bước: phân tích hiện trạng, thiết kế quy trình mới, triển khai và đào tạo. Chúng tôi sẽ cùng doanh nghiệp đánh giá toàn diện các quy trình hiện tại, xác định các điểm nghẽn và đề xuất giải pháp tối ưu.",
        "Easetech is committed to accompanying businesses throughout the implementation process, ensuring the new processes operate efficiently.": "Easetech cam kết đồng hành cùng doanh nghiệp trong suốt quá trình triển khai, đảm bảo quy trình mới được vận hành hiệu quả.",
        "Process Design and Modeling": "Thiết kế, mô hình hóa quy trình",
        "Easetech utilizes modern tools and methods, such as BPMN and UML, to design and model processes. We offer flexible modeling solutions tailored to the specific characteristics and scale of each business.": "Easetech sử dụng các công cụ và phương pháp hiện đại để thiết kế, mô hình hóa quy trình, như BPMN, UML. Chúng tôi cung cấp các giải pháp mô hình hóa linh hoạt, phù hợp với từng đặc thù ngành nghề và quy mô doanh nghiệp.",
        "Predictive Analytics": "Phân tích dự báo",
        "Easetech provides professional predictive analytics services, enabling businesses to make more accurate decisions. By analyzing historical and current data, we develop precise forecasting models that help businesses predict market trends, customer demands, and factors influencing their operations.":"Easetech cung cấp dịch vụ phân tích dự báo chuyên nghiệp, giúp doanh nghiệp đưa ra quyết định kinh doanh chính xác hơn. Bằng việc phân tích dữ liệu lịch sử và hiện tại, chúng tôi xây dựng các mô hình dự báo chính xác, giúp doanh nghiệp dự đoán xu hướng thị trường, nhu cầu khách hàng và các yếu tố ảnh hưởng đến kinh doanh.",
        "Solutions - Services": "Giải pháp - dịch vụ",
        "Solutions": "Giải pháp",
        "Recruitment": "Tuyển dụng",
        "Introduction": "Giới thiệu",
        "Core Values - Vision": "Giá trị cốt lõi - Tầm nhìn",
        "Human Resources Team": "Đội ngũ nhân sự",
        "For Employees": "Đối với nhân viên",
        "Create a Professional Working Environment:": "Tạo môi trường làm việc chuyên nghiệp:",
        "Invest in facilities, technology, and training to create a modern and dynamic working environment.": "Đầu tư vào cơ sở vật chất, công nghệ và đào tạo để tạo ra một môi trường làm việc hiện đại và năng động.",
        "Encourage Creativity and Innovation:": "Khuyến khích sáng tạo và đổi mới:",
        "Create conditions for employees to freely innovate, propose new ideas, and contribute to the company's development.": "Tạo điều kiện để nhân viên tự do sáng tạo, đưa ra những ý tưởng mới và đóng góp vào sự phát triển của công ty.",
        "Ensure good benefits:": "Đảm bảo phúc lợi tốt:",
        "Provide attractive compensation packages, opportunities for advancement, and career development to attract and retain talent.": "Cung cấp các chế độ đãi ngộ hấp dẫn, cơ hội thăng tiến và phát triển nghề nghiệp để thu hút và giữ chân nhân tài.",
        "Core values": "Giá trị cốt lõi",
        "of Easetech are built on the foundation of": "của Easetech được xây dựng trên nền tảng của",
        "innovation, reliability, and collaboration": "sự đổi mới, tin cậy và hợp tác",
        "We are constantly seeking new technologies and innovative solutions to provide our customers with the best experiences. Reliability is the foundation of all relationships; we are committed to accompanying our customers and partners on every journey. Finally, the spirit of collaboration is the key factor that enables us to create outstanding values together.":"Chúng tôi luôn không ngừng tìm kiếm những công nghệ mới, những giải pháp sáng tạo để mang đến cho khách hàng những trải nghiệm tốt nhất. Sự tin cậy là nền tảng cho mọi mối quan hệ, chúng tôi cam kết đồng hành cùng khách hàng và đối tác trên mọi chặng đường. Và cuối cùng, tinh thần hợp tác là yếu tố then chốt để chúng tôi cùng nhau tạo ra những giá trị vượt trội.",
        "Vision": "Tầm nhìn",
        "of EaseTech is to become": "của EaseTech là trở thành",
        "the leading trusted technology partner": "đối tác công nghệ tin cậy hàng đầu",
        "for small and medium-sized enterprises in Vietnam. We aspire to create a world where technology is accessible and beneficial for everyone. EaseTech will continuously strive to simplify technology, helping businesses save time and costs while focusing on core activities. At the same time, we are committed to contributing to": "doanh nghiệp vừa và nhỏ tại Việt Nam. Chúng tôi mong muốn tạo ra một thế giới nơi công nghệ trở nên dễ tiếp cận và hữu ích cho mọi người. EaseTech sẽ không ngừng nỗ lực để đơn giản hóa công nghệ, giúp doanh nghiệp tiết kiệm thời gian, chi phí và tập trung vào những hoạt động cốt lõi. Đồng thời, chúng tôi cũng cam kết đóng góp vào sự",
        "the sustainable development of the community and society.": "phát triển bền vững của cộng đồng và xã hội.",
        "Core Values – Vision": "Giá trị cốt lõi – Tầm nhìn",
        "With over 100 enthusiastic and creative employees, EaseTech proudly boasts a team of top experts in the field of information technology. The diversity of expertise and experience has created a dynamic and effective working environment, where everyone collaborates to solve complex problems and create valuable products and services. The spirit of unity and commitment to common goals has helped us achieve significant success over the years.": "Với hơn 100 nhân viên đầy nhiệt huyết và sáng tạo, EaseTech tự hào sở hữu một đội ngũ chuyên gia hàng đầu trong lĩnh vực công nghệ thông tin. Sự đa dạng về chuyên môn và kinh nghiệm đã tạo nên một môi trường làm việc năng động và hiệu quả, nơi mà mọi người cùng nhau hợp tác để giải quyết các vấn đề phức tạp và tạo ra những sản phẩm, dịch vụ có giá trị. Tinh thần đoàn kết và sự cam kết với mục tiêu chung đã giúp chúng tôi đạt được nhiều thành công trong những năm qua.",
        "Security Services - Information Safety": "Dịch vụ an ninh - An toàn thông tin",
        "Implementation": "Triển khai",
        "Register for Consultation": "Đăng ký nhận tư vấn",
        "Full Name": "Họ tên",
        "Cellphone": "Điện thoại",
        "Content": "Nội dung",
        "Register Now": "Đăng ký ngay",
        "Home Page": "Trang chủ",
        "Key clients of easetech": "Khách hàng tiêu biểu của Easetech",
        "With many years of experience, EASETECH has become a trusted and reputable partner for numerous information technology projects, providing digital transformation solutions for businesses. With an unwavering desire and passion for continuous innovation, Gimasys always strives to fulfill its commitments to customers and partners to the best of its ability.": "Với nhiều năm kinh nghiệm, EASETECH đã trở thành đối tác tin cậy và uy tín cho nhiều dự án công nghệ thông tin, cung cấp các giải pháp chuyển đổi số cho doanh nghiệp. Bằng khát khao và đam mê sáng tạo không ngừng nghỉ, Gimasys luôn cố gắng thực hiện tốt nhất những cam kết của mình dành cho khách hàng và đối tác.",
        "Want to make customers more satisfied and loyal? EaseTech's Contact Center solution will help you do that. With a multi-channel Contact Center system, we enable businesses to interact with customers seamlessly and effectively through phone, email, chat, and social media channels. As a result, businesses can": "Muốn khách hàng hài lòng và trung thành hơn? Giải pháp Contact Center của EaseTech sẽ giúp bạn làm điều đó. Với hệ thống Contact Center đa kênh, chúng tôi giúp doanh nghiệp tương tác với khách hàng một cách liền mạch và hiệu quả qua điện thoại, email, chat, và các kênh truyền thông xã hội. Nhờ đó, doanh nghiệp có thể",
        "quickly capture customer needs, provide professional customer service 24/7, and enhance customer satisfaction": "nắm bắt nhu cầu của khách hàng nhanh chóng, cung cấp dịch vụ khách hàng chuyên nghiệp 24/7, và tăng cường sự hài lòng của khách hàng.",
        "Easetech is committed to accompanying businesses throughout the implementation and operation of the system, ensuring that all activities run smoothly and efficiently.": "Easetech cam kết đồng hành cùng doanh nghiệp trong suốt quá trình triển khai và vận hành hệ thống, đảm bảo mọi hoạt động diễn ra trơn tru và hiệu quả."
    }


};

const getLang = () => {
    const search = window.location.search

    if(search.includes('?language=vi')){
        return 'vi'
    }

    if(search.includes('?language=en')){
        return 'en'
    }

    return 'vi'
}
document.querySelectorAll("[data-key]").forEach(key => {
    console.log("á")
    const lang = getLang()
    const getValue = key.getAttribute('data-key')
    key.innerText = translations[lang][getValue] || key.textContent
})
